version: "3.8"

services:
  postgres:
    container_name: aidbox_etl_pg
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: aidbox
      POSTGRES_USER: aidbox
      POSTGRES_PASSWORD: tF5MdpRxZ9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  aidbox:
    container_name: aidbox_etl
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on:
      - postgres
    ports:
      - "8086:8080"
    environment:
      BOX_ADMIN_PASSWORD: LXo4wI8Qgs
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_DB_PASSWORD: tF5MdpRxZ9
      BOX_DB_PORT: "5432"
      BOX_DB_USER: aidbox
      BOX_LICENSE: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvZmZsaW5lIjpmYWxzZSwiY3JlYXRvciI6eyJpZCI6IjQ3YTFiNjkwLTVmNDUtNDMzOS1iODU3LTllMzNlYjcwMzAwMCIsInJlc291cmNlVHlwZSI6IlVzZXIifSwia2V5Ijoib25saW5lLTIwMjIwNTI0LTE0MzY0NyIsIm5hbWUiOiJBaWRCb3hNeU9ic2VydmF0aW9uIiwiZXhwaXJhdGlvbiI6IjIxMjQtMDQtMTlUMDk6MDM6NTUuNjI3WiIsInR5cGUiOiJkZXZlbG9wbWVudCIsImNyZWF0ZWQiOiIyMDI1LTA1LTEzVDA5OjAzOjU1LjYyN1oiLCJtYXgtaW5zdGFuY2VzIjoyLCJtYXgtZGItc2l6ZSI6NTM2ODcwOTEyMCwicHJvZHVjdCI6ImFpZGJveCIsInByb2plY3QiOnsiaWQiOiIzZTNmMmQ3My1iNTZmLTQzMzEtOWYyMC0zMmZjMGJmZjRlN2IiLCJyZXNvdXJjZVR5cGUiOiJQcm9qZWN0In0sInN0YXR1cyI6ImFjdGl2ZSIsImlkIjoiMTAyZDJkMTctZDM1My00OGIzLWFkZTAtMzY4NjVmMzk4ODBhIiwiaW5mbyI6eyJnb2FsIjoiZGV2ZWxvcG1lbnQiLCJob3N0aW5nIjoic2VsZi1ob3N0ZWQifSwiaXNzdWVyIjoiaHR0cHM6Ly9haWRib3guYXBwIn0.iA0dXFROMyZ_zyrpuas8hOLvyJw-MsD8yIkAFAOBKIcBOnu_Nw5i_8MZutkt_rx_Po98AINOStSrOVPemZp9q33smJApUJuXJgSxWNH_ib2_UsBW453NGmBphevu7aDCfV71CSzi8k91VA-BWzIzSv6g7rGeobm7Qfz_d5oAImA"
      BOX_WEB_BASE_URL: http://localhost:8086
      BOX_WEB_PORT: 8080
      BOX_ROOT_CLIENT_SECRET: _rC3KbnOvW
      BOX_SETTINGS_MODE: read-write
      BOX_SECURITY_DEV_MODE: true
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir

volumes:
  postgres_data:
